### ISSUE TITLE
Update styling to avoid overlap with bootstrap

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#196]
Nav currently looks horrible if bootstrap is loaded. 

![cbtitlebar 1](https://user-images.githubusercontent.com/3680095/31024161-08b3d6d2-a4f3-11e7-8d5b-dded6d663103.png)

**Comment by emmorris** [comment]
According to Rich, the styling issues for codebook within RhoMAP are due to the use of common style names like 'nav' and 'section', which are also used by bootstrap in the RhoMAP UI.  The proposed solution is to prefix common style names with wc- or cb-, etc. to accommodate cases where a given renderer might live inside a page with its own styles.

**Comment by jwildfire** [comment]
Compared codebook css to [this list](https://bootstrapcreative.com/resources/bootstrap-3-css-classes-index/). Need changes for: `.label`, `.nav`, `.nav-tabs` and `.small`

As far as I can tell there is no `.section` css in bootstrap.

**Comment by jwildfire** [comment]
Test Notes: View in CAT after clicking the load bootstrap button (use v1.2.0 for comparison to see wonky formatting)

**Comment by mhickle** [comment]
Pass

![1](https://user-images.githubusercontent.com/31038805/32071397-2e58d566-ba5d-11e7-802f-22ec8661b8b3.PNG)
