### ISSUE TITLE
X-axis labels for character variables

### ISSUE THREAD

**Issue by sjlussier** [RhoInc/web-codebook#279]
It seems that for character variables with very few unique values, the values are displayed to the right of the graphic in a horizontal bar chart. However, when there are more unique values, the chart becomes vertical (which is nice!), but there are no labels for the x-axis. This may be better than only having the pop-up description.

As an example see the following dataset's "site" variable:

```
dat <- tibble(a = rep('01', 100),
              b = sample(c('02', '03', '07', '09'), 100, replace = T),
              c = sample(1000:9999, 100, replace = T)) %>%
  mutate(id = glue("{a}-{b}-{c}"),
         site = sample(c("bost", "nyc", "phil", "chic", "la", "sd", "sf"), 100, replace = T)) %>%
  select(id, site)
```

![image](https://user-images.githubusercontent.com/41168885/43660588-75cd45dc-972d-11e8-8f9f-77b06b8730e2.png)

**Comment by jwildfire** [comment]
Labels are tricky since they will start to overlap once N is large enough.  Instead, we've set it up so the user can actually specify the point when a chart flips from horizontal to vertical bars using [this setting](https://github.com/RhoInc/web-codebook/wiki/Configuration#settingslevelsplit). Default is 5 (which is maybe a little low), but one could definitely bump that up a bit if there are variables where you want the labels shown.
