### ISSUE TITLE
Only render current rows of data table ...

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/web-codebook#55]
... instead of rendering everything and then showing/hiding the current selection.

**Comment by brittsikora** [comment]
This bug is still popping up for me.

To reproduce:
1. Pull up CAT in FireFox: https://jwildfire.github.io/CAT/
2. Confirm the renderer is web-codebook renderer
3. Input version as: ded094eb632f242925acb51f4d9fee867eeeb46d
4. Confirm data file is safetyData-queries/ADAE.csv
5. Click "Render Chart"
6. Click the grey arrow next to the USUBJID to expand the chart
7. Watch the chart expand for all eternity

**Comment by brittsikora** [comment]
Seems to only happens with categorical variables with >5 levels..may have something to do with whatever was done for #44

**Comment by jwildfire** [comment]
Happening for me in FF (but not Chrome). Seems to be an issue with the makeToolTip() for the levelPlot. 

`var dimensions = text[0][0].getBBox();`

**Comment by jwildfire** [comment]
@brittsikora I actually don't think the bug fits well with this issue. Can you just create a new issue with the details listed above (and a screenshot)

**Comment by brittsikora** [comment]
Expected Result: When inspecting an element, there should only be around 25 <tr>s instead of thousands. Jeremy screenshared and confirmed this

Outcome: Pass
