### ISSUE TITLE
Highlight selected subpopulation in all charts

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/web-codebook#59]
Came up in the SDF meeting on 4/13. Karen Boyle said it would be nice if we could select a sub-population and see that cohort on other charts in the Codebook, like JMP offers.

**Comment by jwildfire** [comment]
We've done things like this before, but this is a fairly complex change, and I'm not sure it would actually be used all that much. Would need to figure out the best way to let a user highlight a part of the domain and then add an overlay to every display showing that data. Would be even more complicated in grouped/paneled data. 

Leaning towards waiting to see if the request comes up again. Definitely leaving it out of v1.1 and v1.2.

**Comment by jwildfire** [comment]
On second thought - going to (tentatively) add this to v1.2 since I think it might sync up with #97. Will need to have some design discussions about how this would work.

**Comment by emmorris** [comment]
Example is the Microbiota Explorer.  You could pick both old and young people as a population of interest.

**Comment by jwildfire** [comment]
__Technical Specs__

After #97, add the following functionality to the summaryTable:

1. Add an overlay to each chart that shows the distribution of the highlighted data on that chart.
   - use `stroke:black`, `fill:white`
2. Update `codebook.controls.highlights.clear()` to remove/hide the highlighted bars.

Implementation of the above functionality isn't trivial since the data flow for each chart is so custom and is implemented across several different functions. My best guess is that `codebook.data.makeSummary` will need to be updated with a new method that creates summary statistics for the `highlighted` data in addition to the `filtered` data stream, and then each of the `charts.createChart` functions will have to be customized as well. If possible, it would be nice to draw the bars with a new item in the chart's `marks` array, but might need to fallback to custom marks drawn on re-size instead.

**Comment by jwildfire** [comment]
Test Notes: See [here](https://github.com/RhoInc/web-codebook/issues/97#issuecomment-319479478)

**Comment by brittsikora** [comment]
Pass

Histogram, grouped
![97_histogram_grouped](https://user-images.githubusercontent.com/14914918/28846766-a283bc74-76da-11e7-90f2-0898cac8066b.JPG)

Histogram, ungrouped
![97_histogram_ungrouped](https://user-images.githubusercontent.com/14914918/28846777-abc45370-76da-11e7-9b26-bb15fa9fd590.JPG)

Vertical bar chart, grouped
![97_vertical_grouped](https://user-images.githubusercontent.com/14914918/28846779-af2930b2-76da-11e7-8744-cc58267bea5c.JPG)

Vertical bar chart, ungrouped
![97_vertical_ungrouped](https://user-images.githubusercontent.com/14914918/28846782-b123870a-76da-11e7-8c03-eb7651d8969d.JPG)

Horizontal bar chart, grouped
![97_horizontal_grouped](https://user-images.githubusercontent.com/14914918/28846787-b3d37f46-76da-11e7-9fb1-1f6dc0c3f376.JPG)

Horizontal bar chart, ungrouped
![97_horizontal_ungrouped](https://user-images.githubusercontent.com/14914918/28846797-bc8482ac-76da-11e7-98cb-32997929c4ff.JPG)
